# Generated by Django 3.0.3 on 2020-02-15 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('baseuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('number', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='farmer.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('quality_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_type', models.CharField(choices=[('CP', 'Crop Product'), ('AP', 'Animal Product')], default='CP', max_length=3)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_product', to='farmer.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=32)),
                ('crop_type', models.CharField(max_length=32)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop', to='farmer.Farmer')),
            ],
        ),
    ]
