# Generated by Django 3.0.3 on 2020-02-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20200215_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_type', models.CharField(choices=[('CP', 'Crop Product'), ('AP', 'Animal Product')], default='CP', max_length=3)),
                ('quality_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_per_kg', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='number',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='livestock',
            name='avg_age',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cash Crop'), ('FC', 'Food Crop'), ('PC', 'Plantation Crop'), ('HC', 'Horticulture Crop')], default='CC', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='lati',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='longi',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='FarmerProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='farmer.Farmer'),
        ),
    ]
