# Generated by Django 3.0.3 on 2020-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(blank=True, choices=[('ADM', 'Admin'), ('FMR', 'Farmer'), ('SPL', 'Supplier'), ('RTL', 'Retailer'), ('LLD', 'Landlord')], default='ADM', max_length=3, null=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('active', models.IntegerField(choices=[(-1, 'NOT ACTIVE'), (0, 'NEW USER'), (1, 'ACTIVE')], default=-1)),
                ('staff', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'BaseUser',
                'verbose_name_plural': 'BaseUsers',
            },
        ),
    ]
