# Generated by Django 3.0.3 on 2020-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='active',
            field=models.IntegerField(choices=[(-1, 'NOT ACTIVE'), (0, 'NEW USER'), (1, 'ACTIVE')], default=0),
        ),
    ]
