# Generated by Django 3.0.3 on 2020-02-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='staff',
        ),
    ]
